steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/suricata:2006', 'docker/suricata/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/p0f:2006', 'docker/p0f/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/fatt:2006', 'docker/fatt/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/logstash:2006', 'docker/elk/logstash']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/elasticsearch:2006', 'docker/elk/elasticsearch']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/kibana:2006', 'docker/elk/kibana']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/head:2006', 'docker/elk/head']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/cowrie:2006', 'docker/cowrie/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/dionaea:2006', 'docker/dionaea/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/elasticpot:2006', 'docker/elasticpot/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/honeytrap:2006', 'docker/honeytrap/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/mailoney:2006', 'docker/mailoney/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/medpot:2006', 'docker/medpot/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/rdpy:2006', 'docker/rdpy/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/spiderfoot:2006', 'docker/spiderfoot/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/snare:2006', 'docker/tanner/snare']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/tanner_api:2006', 'docker/tanner/tanner']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/tanner_phpox:2006', 'docker/tanner/phpox']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/tanner_redis:2006', 'docker/tanner/redis']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/honeypy:2006', 'docker/honeypy/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/dicompot:2006', 'docker/dicompot/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/cyberchef:2006', 'docker/cyberchef/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/honeysap:2006', 'honeysap/honeysap/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/heralding:2006', 'docker/heralding/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/heimdall:2006', 'docker/heimdall/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/conpot:2006', 'docker/conpot/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/citrixhoneypot:2006', 'docker/citrixhoneypot/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/adbhoney:2006', 'docker/adbhoney/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/ewsposter:2006', 'docker/ews/']
timeout: 2400s
images:
- 'us.gcr.io/$PROJECT_ID/suricata:2006'
- 'us.gcr.io/$PROJECT_ID/p0f:2006'
- 'us.gcr.io/$PROJECT_ID/fatt:2006'
- 'us.gcr.io/$PROJECT_ID/kibana:2006'
- 'us.gcr.io/$PROJECT_ID/elasticsearch:2006'
- 'us.gcr.io/$PROJECT_ID/logstash:2006'
- 'us.gcr.io/$PROJECT_ID/head:2006'
- 'us.gcr.io/$PROJECT_ID/adbhoney:2006'
- 'us.gcr.io/$PROJECT_ID/ewsposter:2006'
- 'us.gcr.io/$PROJECT_ID/citrixhoneypot:2006'
- 'us.gcr.io/$PROJECT_ID/conpot:2006'
- 'us.gcr.io/$PROJECT_ID/heimdall:2006'
- 'us.gcr.io/$PROJECT_ID/heralding:2006'
- 'us.gcr.io/$PROJECT_ID/honeypy:2006'
- 'us.gcr.io/$PROJECT_ID/honeysap:2006'
- 'us.gcr.io/$PROJECT_ID/honeytrap:2006'
- 'us.gcr.io/$PROJECT_ID/dicompot:2006'
- 'us.gcr.io/$PROJECT_ID/dionaea:2006'
- 'us.gcr.io/$PROJECT_ID/elasticpot:2006'
- 'us.gcr.io/$PROJECT_ID/cyberchef:2006'
- 'us.gcr.io/$PROJECT_ID/cowrie:2006'
- 'us.gcr.io/$PROJECT_ID/snare:2006'
- 'us.gcr.io/$PROJECT_ID/tanner_api:2006'
- 'us.gcr.io/$PROJECT_ID/tanner_redis:2006'
- 'us.gcr.io/$PROJECT_ID/tanner_phpox:2006'
- 'us.gcr.io/$PROJECT_ID/rdpy:2006'
- 'us.gcr.io/$PROJECT_ID/spiderfoot:2006'
- 'us.gcr.io/$PROJECT_ID/medpot:2006'
- 'us.gcr.io/$PROJECT_ID/mailoney:2006'
