# T-Pot Image Builder (use only for building docker images)
version: '2.3'

services:

##################
#### Honeypots
##################

# Adbhoney service
  adbhoney:
    build: adbhoney/.
    image: "us.gcr.io/neutralthreat/adbhoney:2006"

# Ciscoasa service
  ciscoasa:
    build: ciscoasa/.
    image: "us.gcr.io/neutralthreat/ciscoasa:2006"

# CitrixHoneypot service
  citrixhoneypot:
    build: citrixhoneypot/.
    image: "us.gcr.io/neutralthreat/citrixhoneypot:2006"

# Conpot IEC104 service
  conpot_IEC104:
    build: conpot/.
    image: "us.gcr.io/neutralthreat/conpot:2006"

# Cowrie service
  cowrie:
    build: cowrie/.
    image: "us.gcr.io/neutralthreat/cowrie:2006"

# Dicompot service
  dicompot:
    build: dicompot/.
    image: "us.gcr.io/neutralthreat/dicompot:2006"

# Dionaea service
  dionaea:
    build: dionaea/.
    image: "us.gcr.io/neutralthreat/dionaea:2006"

# ElasticPot service
  elasticpot:
    build: elasticpot/.
    image: "us.gcr.io/neutralthreat/elasticpot:2006"

# Glutton service
  glutton:
    build: glutton/.
    image: "us.gcr.io/neutralthreat/glutton:2006"

# Heralding service
  heralding:
    build: heralding/.
    image: "us.gcr.io/neutralthreat/heralding:2006"

# HoneyPy service
  honeypy:
    build: honeypy/.
    image: "us.gcr.io/neutralthreat/honeypy:2006"

# Honeytrap service
  honeytrap:
    build: honeytrap/.
    image: "us.gcr.io/neutralthreat/honeytrap:2006"

# Mailoney service
  mailoney:
    build: mailoney/.
    image: "us.gcr.io/neutralthreat/mailoney:2006"

# Medpot service
  medpot:
    build: medpot/.
    image: "us.gcr.io/neutralthreat/medpot:2006"

# Rdpy service
  rdpy:
    build: rdpy/.
    image: "us.gcr.io/neutralthreat/rdpy:2006"

#### Snare / Tanner
## Tanner Redis Service
  tanner_redis:
    build: tanner/redis/.
    image: "us.gcr.io/neutralthreat/redis:2006"

## PHP Sandbox service
  tanner_phpox:
    build: tanner/phpox/.
    image: "us.gcr.io/neutralthreat/phpox:2006"

## Tanner API Service
  tanner_api:
    build: tanner/tanner/.
    image: "us.gcr.io/neutralthreat/tanner:2006"

## Snare Service
  snare:
    build: tanner/snare/.
    image: "us.gcr.io/neutralthreat/snare:2006"


##################
#### NSM
##################

# Fatt service
  fatt:
    build: fatt/.
    image: "us.gcr.io/neutralthreat/fatt:2006"

# P0f service
  p0f:
    build: p0f/.
    image: "us.gcr.io/neutralthreat/p0f:2006"

# Suricata service
  suricata:
    build: suricata/.
    image: "us.gcr.io/neutralthreat/suricata:2006"


##################
#### Tools
##################

# Cyberchef service
  cyberchef:
    build: cyberchef/.
    image: "us.gcr.io/neutralthreaty/cyberchef:2006"

#### ELK
## Elasticsearch service
  elasticsearch:
    build: elk/elasticsearch/.
    image: "us.gcr.io/neutralthreat/elasticsearch:2006"

## Kibana service
  kibana:
    build: elk/kibana/.
    image: "us.gcr.io/neutralthreat/kibana:2006"

## Logstash service
  logstash:
    build: elk/logstash/.
    image: "us.gcr.io/neutralthreat/logstash:2006"

## Elasticsearch-head service
  head:
    build: elk/head/.
    image: "us.gcr.io/neutralthreat/head:2006"

# Ewsposter service
  ewsposter:
    build: ews/.
    image: "us.gcr.io/neutralthreat/ewsposter:2006"

# Nginx service
  nginx:
    build: heimdall/.
    image: "us.gcr.io/neutralthreat/nginx:2006"

# Spiderfoot service
  spiderfoot:
    build: spiderfoot/.
    image: "us.gcr.io/neutralthreat/spiderfoot:2006"
